### ISSUE TITLE
JavaScript Testing: Refactor section and outline some important concepts 

### ISSUE THREAD

**Issue by nikitarevenco** [TheOdinProject/curriculum#27517] opened 2024-03-02 00:27 UTC
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

This issue used to be solely about the Battleship project. However, after some discussions with @cakegod  and @MaoShizhong , the testing section could see some general improvement.

### More Testing lesson (part 2) - Credit to @cakegod for the ideas. [Check out the discord message and our discussion](https://discord.com/channels/505093832157691914/505093832157691916/1213300957895598140).  
<img src='https://github.com/TheOdinProject/curriculum/assets/154856872/6c0f2242-9db2-4f25-b838-47e0c28cfd80' height='auto' width='100%'>

#### Adding on to what Cake said
- Mention how tests should be isolated from one another and they should all pass even when ran in a random order with `--randomize` flag.
- **Open question**: Is there a need for the learner to know about what Mocking is for the Battleship project? I personally haven't used this. If it's **not** needed, then why should the lesson go over it? Wouldn't it be better to leave mocking for the React testing section? I personally didn't use mocking and I have very little experience with it - so I'm asking whoever is more knowledgeable about the topic to provide some insight

### Testing practice project 
- Right now, the project touches on creating some basic methods that capitalise a string for example. While this is fine to get a very basic overview of testing, it's not enough to prepare the learner for the testing in Battleship project. 
- My idea is to move the project to be before the Battleship section, the reason why is so that learners can use what they learned in the 2nd lesson and apply it on the testing practice. This should prepare them better for Battleship testing
- This way the project can be made more advanced to serve as really good practice for battleship. 

### Battleship Project
- Remove too much `guidance`, for example the project tells the learner **exactly** what should be done. e.g. create a `Ship` class, it has a `hit()` method etc. 
- This won't necessarily make the project more difficult. Rather, this may actually *simplify* it because people that follow the instructions on the page could be sent down the wrong path and instead try a solution that TOP recommends when figuring out on their own would've been faster and easier to do.
- I experienced this first-hand, I've spent so much time trying to do it the way TOP says in the project specification only to approach it in a completely different way and the solution that I came up with was so much simpler for me to implement. 
- By this point the learner will have done a **lot** of javascript projects. They should be able to come up with their own implementation. What they *haven't* had practice with before at proper scale would be TDD. In that case, it could be considered appropriate to **increase** guidance in relation to the TDD and **decrease** the guidance for actual logic.

<Details>
<Summary>
How the extra guidance regarding logic could be changed to be more open and up to learner's implementation. Note this doesn't cover any changes to the testing part of the guidance.
</Summary>

1. Your ships should be able to receive hits, and when a ship doesn't have any more living segments it should become sunk.

2. The area around sunk ships should be automatically marked as hit 

3. You should be able to place ships at specific coordinates on the board 

4. Each player can take turns by attacking the enemy board. Since the game is played against the computer, it should be able to randomly place ships and place random moves. It should *not* break rules of the game, e.g. hitting the same cell twice in a 
row. 

5. Each player should see all ships on their board, but they should only see the enemy's board's cells only if that cell was hit, otherwise they will see an empty cell.

6. At this point it is appropriate to craft the user interface, make a visual display of the current player's board and a copy of the enemy's board, where only the cells that have been hit before are shown. 

7. The players should be able to click on a coordinate on the screen and that cell on the enemy's board will receive the hit

8. Once all ships have been destroyed, determine the winner. 

9. Implement the system that allows players to place the ships by having a button to cycle through ship coordinates or letting them type in coordinates.
</Details>

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-javascript-battleship

### (Optional) Discord Name

Revenco

**Comment by cakegod** [comment] 2024-03-02 00:47
I disagree. The main goal of this project is to adopt the TDD approach rather than focus on implementation. Furthermore, based on what I have witnessed in the help channels, this project seems to be one of the most challenging. If we reduce the guidance, Odionites will likely have even more difficulty and, therefore, need more help and, thus, more guidance.

**Comment by MaoShizhong** [comment] 2024-03-02 01:00
I'm inclined to agree with @cakegod on this one.
I don't actually personally feel strongly about the inclusion or exclusion of the examples you mentioned/draft outline, meaning I'm not so convinced there's any significant value gained from reducing those parts.

@TheOdinProject/javascript thoughts?

**Comment by nikitarevenco** [comment] 2024-03-02 01:03
> I'm inclined to agree with @cakegod on this one. I don't actually personally feel strongly about the inclusion or exclusion of the examples you mentioned/draft outline, meaning I'm not so convinced there's any significant value gained from reducing those parts.
> 
> @TheOdinProject/javascript thoughts?

> I disagree. The main goal of this project is to adopt the TDD approach rather than focus on implementation. Furthermore, based on what I have witnessed in the help channels, this project seems to be one of the most challenging. If we reduce the guidance, Odionites will likely have even more difficulty and, therefore, need more help and, thus, more guidance.

Thing is, I don't actually feel like reducing guidance will make the project harder per say. I don't know how others did it, but from personal experience following how TOP suggests the project to be done (e.g. with Player class, Ship class) made me waste a lot of time and when I came up with my own solution it was way more straightforward.

Also by this point the learner will have done **a lot** of javascript projects so they should really be able to come up with their own implementation. What they *haven't* had practice with before at proper scale would be TDD, so in that case, it could be considered appropriate to **increase** guidance in relation to the TDD and **decrease** for actual logic

**Comment by MaoShizhong** [comment] 2024-03-02 01:10
While I'm still not 100% convinced there's a significant *need* to reduce content in the spec relating to the actual logic/implementation, amending it to add additional guidance related to the TDD side is a very different thing and I'd certainly be interested to hear your thoughts on what sort of ways this could be implemented and how they might solve certain problems.

I'm well aware this project on the testing front is tough, given it's the first venture into writing own tests outside of small isolated exercises. Granted, I haven't spent as much time helping people in the Discord server with these testing parts specifically as some others have. So it would be interesting to hear about what sort of common problems have been faced, and if they seem like disproportionate problems for this project, how those problems might be aided.

**Comment by nikitarevenco** [comment] 2024-03-02 01:12
> I disagree. The main goal of this project is to adopt the TDD approach rather than focus on implementation. Furthermore, based on what I have witnessed in the help channels, this project seems to be one of the most challenging. If we reduce the guidance, Odionites will likely have even more difficulty and, therefore, need more help and, thus, more guidance.

Given that you've helped many people, do you have any ideas for what people usually struggle with on this project and what could be improved about it for example? 

If anyone else has any comments on this please put them down below, whether general or personal.

**Comment by cakegod** [comment] 2024-03-02 02:03
This is quite a difficult question because the questions are quite diverse. 

Although I have a [few ideas](https://discord.com/channels/505093832157691914/505093832157691916/1213300957895598140) of what could be covered or/and improved. However, not necessarily in the battleship project. Once we cover those things, we can provide hints with those in mind.

**Comment by nikitarevenco** [comment] 2024-03-02 11:46
@cakegod @MaoShizhong I have updated the original issue to reflect the new ideas / thoughts.

**Comment by MaoShizhong** [comment] 2024-04-03 23:57
Revisiting this, as far as the Battleship project is concerned,. I'm really not sure we need to do much if anything to it for now. From what I've seen, the Battleship-related points raised here haven't been particular pain points over the last few months, so I'm very reluctant to make any significant changes to it if there haven't been.

As for the testing lessons, I know @cakegod has more awareness of what's going on with potential pain points in the community. His suggestions make sense to me, I agree would be extremely helpful fundamental knowledge to have a clearer awareness of, and I don't think would lead to much of a drastic change to the testing lesson(s). I'm strongly in the camp of "don't make big changes to a lesson unless there's a very strong argument for why it needs it".

If Cake is happy to do so, I'd like to see what they suggest in a PR, where details can be reviewed as needed. 
I know you checked the assignment box @nikitarevenco but given the nature of the issue changed a lot, and the main points for the current issue state were brought about by Cake based om his experience helping in the testing channel, hope it makes sense why I'd extend the assignment offer to them in this case.

**Comment by MaoShizhong** [comment] 2024-04-04 00:01
As for mocking, not everyone will feel they need to use it but it is something that can be used, and is a somewhat big part of testing in general.
You can mock functions to return specific values in order to test specific cases. You can also mock functions and check if an oute rfunction calls them, without needing to run the called function itself, as the test may not care about how that function works i.e. testing your outer function does not rely on the inner function working, especially if the inner function is already tested elsewhere. Yiu may just want to know the inner function gets called, but by mocking it, you don't need to actually run it, and can continue testing the outer function as intended.

**Comment by cakegod** [comment] 2024-04-06 13:56
I've always found it odd how the testing section is focused on TDD instead of *testing in general*. I think optimally, we should first start explaining what testing *is* before teaching testing techniques/methodologies.

If I am going to address this, it will have to be through new lessons and also require the current "testing" lessons to be slightly revamped.

**Comment by MaoShizhong** [comment] 2024-04-06 14:14
In that case, @cakegod, that seems like something much more appropriate for you to write a separate issue yourself on if it's something you wish to propose and work on. More so than "converting" this issue from what it originally was into that much larger proposal, with your ideas in the comments rather than the issue body.

What I'll do then is close this issue, as I don't think the original proposal needs action.
If you wish to open a separate issue with your proposal for the testing lessons, then I'll leave that to you whenever you have time to do so, then any further discussion can occur there.

**Closed by MaoShizhong** 2024-04-06 14:14 UTC
