### ISSUE TITLE
Introduction To State: CodeSandbox is out of credits?

### ISSUE THREAD

**Issue by djcrago** [TheOdinProject/curriculum#27473] opened 2024-02-27 22:51 UTC
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

![Screenshot 2024-02-27 at 3 46 38 PM](https://github.com/TheOdinProject/curriculum/assets/141692399/7c1c9fb2-6948-484f-bb4e-677781a4904a)

I am unsure if this something I have done or not. Thanks for letting me know!
(I know it says I can fork it to still see it, but I am assuming this is not the intended method of viewing this content.)

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-react-new-introduction-to-state

**Comment by KevinMulhern** [comment] 2024-02-27 22:54
Thanks for reporting @djcrago - duplicate of https://github.com/TheOdinProject/curriculum/issues/27253

**Closed by KevinMulhern** 2024-02-27 22:54 UTC

**Comment by djcrago** [comment] 2024-02-28 03:14
Thanks! Sorry for the duplicate. I didn’t see #27253 when I looked under the React labelOn Feb 27, 2024, at 3:55 PM, Kevin ***@***.***> wrote:﻿
Thanks for reporting @djcrago - duplicate of #27253
