### ISSUE TITLE
website will refuse to connect without the "www." at the start 

### ISSUE THREAD

**Issue by Spayco** [TheOdinProject/curriculum#13293] opened 2019-11-24 15:37 UTC
https://theodinproject.com/ won't work unless you add the `www.` at the start.

**Comment by dvik1950** [comment] 2019-11-30 14:31
It's been addressed here : https://github.com/TheOdinProject/theodinproject/issues/930 :)

**Comment by mindovermiles262** [comment] 2019-12-18 17:42
Duplicate of #930

**Closed by mindovermiles262** 2019-12-18 17:42 UTC
