### ISSUE TITLE
Grammatical error on Javascript Basics/Foundamentals Part I

### ISSUE THREAD

**Issue by 91Flavio91** [TheOdinProject/curriculum#24325] opened 2022-07-01 17:18 UTC
Hi! I noticed that there is an unecessary question mark on the Javascript Basics/Foundamentals Part I. If you go on the "Knowledge Check" section and take a look at the first link, you will spot the unecessary question mark. I mean, I found it unecessary because the sentence sounds affirmative!

[JS Fundamentals Part 1 knowledge check](https://www.theodinproject.com/lessons/foundations-fundamentals-part-1#knowledge-check)

**Comment by SaadShah11** [comment] 2022-07-01 20:40
The question mark seems correctly placed; not all questions start with what, when, where, why, how etc. This sentence is grammatically correct with and without the ? so it seems unnecessary to remove it.

**Comment by Overlandcoder** [comment] 2022-07-01 23:19
> The question mark seems correctly placed; not all questions start with what, when, where, why, how etc. This sentence is grammatically correct with and without the ? so it seems unnecessary to remove it.

I think the question mark would only make sense if the sentence was changed to "Can you name the three ways to declare a variable?". Otherwise it should be removed.

**Comment by fortypercenttitanium** [comment] 2022-07-03 16:04
The issue is correct, the question mark doesn't belong there. @91Flavio91 Would you like to be assigned?

**Comment by 91Flavio91** [comment] 2022-07-03 19:27
@fortypercenttitanium yes I would, thank you!

**Comment by mrmchughes** [comment] 2022-07-15 17:38
Is this still open?

**Comment by Frittenfred97** [comment] 2022-07-15 23:12
that i was asking my self also :D

**Comment by 91Flavio91** [comment] 2022-07-15 23:28
@mrmchughes @Frittenfred97 I’ve corrected the error a few days ago but I’m waiting for someone to let me know. On the contribution guide is written to wait after to have pulled. Let’s wait!

**Comment by ericjmorey** [comment] 2022-07-22 20:40
Is this still open?

It looks like the change was merged but the change removes the "?" without replacing it with a "."

**Comment by fortypercenttitanium** [comment] 2022-07-22 20:42
> Is this still open?
> 
> It looks like the change was merged but the change removes the "?" without replacing it with a "."
> 

It should have closed. We're not concerned about a missing period. Thanks for the help!

**Closed** 2022-07-22 20:42 UTC
Labels: Type: Good First Issue, Status: Help Wanted, Type: Easy Fix
