### ISSUE TITLE
Introduction To State: CodeSandbox out of Credits

### ISSUE THREAD

**Issue by djcrago** [TheOdinProject/curriculum#27475] opened 2024-02-27 23:02 UTC
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

![Screenshot 2024-02-27 at 3 46 38 PM](https://github.com/TheOdinProject/curriculum/assets/141692399/f047645b-3d59-41f8-a8b8-828ed0e610ae)

This was displayed instead of the actual content.

![Screenshot 2024-02-27 at 3 54 08 PM](https://github.com/TheOdinProject/curriculum/assets/141692399/3c698553-d4ba-446d-a463-cc3d2917cd9c)

When I tried forking it myself this is the message I received.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-react-new-introduction-to-state

**Comment by KevinMulhern** [comment] 2024-02-28 11:39
Thanks for reporting @djcrago - duplicate of https://github.com/TheOdinProject/curriculum/issues/27253

**Closed by KevinMulhern** 2024-02-28 11:39 UTC
