### ISSUE TITLE
Introduction to Web Development: <Short description of your suggestion>

### ISSUE THREAD

**Issue by devCarlosZ** [TheOdinProject/curriculum#26769] opened 2023-11-18 18:36 UTC
### Describe your suggestion

You get a 404 error on the link to "Why Learning to Code is So Damn Hard" page.

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-introduction-to-web-development

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### (Optional) Additional Comments

I believe the article you reference either was moved or replicated in [Mediium](https://medium.com/@andrewlatta/why-learning-to-code-is-so-damn-hard-303eae632820). I googled the title and found a [Linked-in](https://www.linkedin.com/posts/ramona-e-452907251_why-learning-to-code-is-so-damn-hard-thinkful-activity-7089628091152576512-2L-I) entry that made reference to your link and it contain content-headings from the medium post. 

Hope this helps!

Carlos

**Comment by aconstas** [comment] 2023-11-18 18:50
Here's the article from [web.archive.org](https://web.archive.org/web/20231104194146/https://www.thinkful.com/blog/why-learning-to-code-is-so-damn-hard/)

**Comment by KevinMulhern** [comment] 2023-11-20 17:12
Thanks for reporting - duplicate of https://github.com/TheOdinProject/curriculum/issues/26753

**Closed by KevinMulhern** 2023-11-20 17:12 UTC
