### ISSUE TITLE
JavaScript Basics: Outdated/Incorrect output on Debug JavaScript in Chrome Devtools 

### ISSUE THREAD

**Issue by ZackHoang** [TheOdinProject/curriculum#25722] opened 2023-07-02 03:45 UTC
### Describe your suggestion

I was working through JavaScript Developer Tools in Foundations -> JavaScript Basics and noticed an error in the Debug JavaScript tutorial on Chrome Devtools. On step 3, section number 4, here is what it says: 

![Screenshot from 2023-07-02 10-33-09](https://github.com/TheOdinProject/curriculum/assets/130317776/3b08938a-989c-4a42-a86b-5c6e3499ba43)

Even when following all the instructions correctly, it always stops at the second line of the function definition, here's my output: 

![Screenshot from 2023-07-02 10-36-31](https://github.com/TheOdinProject/curriculum/assets/130317776/e9739cd2-7563-4bc5-8df0-65c2a8a9c878)

A similar issue was opened but I think it is not resolved yet (https://github.com/GoogleChrome/developer.chrome.com/issues/2947) 

This is an issue from the Chrome Devtools themselves which understandably, TOP might not be able to fix. However, I do suggest a new link that covers the same content to be replaced here, 

### Path

Foundations

### Lesson Url

https://developer.chrome.com/docs/devtools/javascript/#code-stepping

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### (Optional) Discord Name

zackattack2507

**Comment by CouchofTomato** [comment] 2023-07-02 21:19
Thanks @ZackHoang 

Have you come across a suitable link we could replace it with.

**Comment by ZackHoang** [comment] 2023-07-03 01:30
> Thanks @ZackHoang
> 
> Have you come across a suitable link we could replace it with.

Unfortunately no, I haven't came across anything yet. I'll Google around and take a few links that might work.

**Comment by CouchofTomato** [comment] 2023-07-03 07:41
Thanks @ZackHoang 

You don't need to spend a ton of time on it. Maybe for now we could add a warning against the text for that resource. Do you think that would help?

**Comment by ZackHoang** [comment] 2023-07-03 08:19
> Thanks @ZackHoang
> 
> You don't need to spend a ton of time on it. Maybe for now we could add a warning against the text for that resource. Do you think that would help?

Certainly! I think a quick note about the error will suffice. One thing to note though is that I am not entirely sure how much this error impacts the tutorial as a whole because I haven't finished it myself. Regardless, I think Odin learners should still be informed about this. 

Thank you!

**Comment by CouchofTomato** [comment] 2023-07-03 08:35
@ZackHoang Thanks for the feedback.

If you do come across any issues because of this when you do finish the tutorial please let us know.

In the meantime for the warning you haven't indicated you'd like to work on a solution. Just checking whether it is something you wanted to tackle before I open it up for others to work on?

**Comment by ZackHoang** [comment] 2023-07-03 08:45
> @ZackHoang Thanks for the feedback.
> 
> If you do come across any issues because of this when you do finish the tutorial please let us know.
> 
> In the meantime for the warning you haven't indicated you'd like to work on a solution. Just checking whether it is something you wanted to tackle before I open it up for others to work on?

Please pass it on to others, I'll finish up the tutorial some times on my own and note any other issues.

**Comment by CouchofTomato** [comment] 2023-07-03 09:05
For anyone that wants to work on this

This is the lesson - https://www.theodinproject.com/lessons/foundations-understanding-errors
Github: https://github.com/TheOdinProject/curriculum/blob/main/foundations/javascript_basics/understanding_errors.md#tips-for-resolving-errors

We need to add a warning to where we link to [this lesson](https://developer.chrome.com/docs/devtools/javascript/) in the tips for resolving errors section. We need to mention that in point 4 of step 3 of the tutorial it mentions a breakpoint will stop at the line where the function declares but there is a [known issue](https://github.com/GoogleChrome/developer.chrome.com/issues/2947) we can link to where it may stop on the second line of the function instead. Learners shouldn't panic if this happens.

**Comment by Mclilzee** [comment] 2023-07-03 12:35
I would change the wording of that, It is not an issue with Devtools but the issue is in the article itself writing outdated information. Chrome Devtools pauses on the first line of a function as  intended, Same behaviour works on Firefox, in fact in firefox you can't even click a function name, you can only make a breakpoint on the first line of a function.

They made this change because there is no point to pause on a function name, because it serves same no purpose to do so, when a function is called it's body gets executed.

**Comment by CouchofTomato** [comment] 2023-07-03 13:11
Thanks @Mclilzee 

I've added a comment to the PR to amend more in line with what you've said.

**Closed** 2023-07-03 18:09 UTC
Labels: Status: Help Wanted, Type: Easy Fix, Content: Intermediate HTML/CSS
