### ISSUE TITLE
Intermediate HTML and CSS Course/Introduction: Broken link

### ISSUE THREAD

**Issue by roman-thapa** [TheOdinProject/curriculum#24908] opened 2022-11-18 03:52 UTC
### Describe your suggestion

There is a broken link in Node JS path's Intermediate HTML and CSS Course [Introduction](https://www.theodinproject.com/lessons/node-path-intermediate-html-and-css-introduction) lesson 
In [Introduction lesson's aassignment](https://www.theodinproject.com/lessons/node-path-intermediate-html-and-css-introduction#assignment) second assignment link for CSS Cheat Sheet is broken.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-intermediate-html-and-css-introduction

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

**Comment by ChargrilledChook** [comment] 2022-11-18 10:11
Hi @roman-thapa , thanks for making a report.

When I try the link ([this one](https://websitesetup.org/wp-content/uploads/2019/11/wsu-css-cheat-sheet-gdocs.pdf)) it seems to work fine. Is that the one you were having trouble with?

On desktop it links to a PDF file, on mobile I get the option to save / download it. Is there any more information you can provide?

**Comment by roman-thapa** [comment] 2022-11-21 10:13
Hello @ChargrilledChook thank you for the response.

Yes, I'm talking about the [same link](https://websitesetup.org/wp-content/uploads/2019/11/wsu-css-cheat-sheet-gdocs.pdf) I had tried to access that link through laptop and mobile too but it shows Access denied Error code 1020.

**Comment by ChargrilledChook** [comment] 2022-11-26 05:44
> Hello @ChargrilledChook thank you for the response.
> 
> Yes, I'm talking about the [same link](https://websitesetup.org/wp-content/uploads/2019/11/wsu-css-cheat-sheet-gdocs.pdf) I had tried to access that link through laptop and mobile too but it shows Access denied Error code 1020.

No worries @roman-thapa. 

As I mentioned the link seems fine on my end - [googling the error code](https://www.google.com/search?q=1020+error+code&oq=1020+error) it looks like this could be something that's caused by your firewall or VPN. 

Since this isn't something we can control your best bet may be to see if there are any workarounds. 

I'm going to close this issue, but message me here if you need any more clarification :+1:

**Closed by ChargrilledChook** 2022-11-26 05:44 UTC
Labels: Content: Intermediate HTML/CSS
