### ISSUE TITLE
React: Error when running test due to outdated version of @testing-library/user-event

### ISSUE THREAD

**Issue by mosmn** [TheOdinProject/curriculum#25804] opened 2023-07-15 07:54 UTC
### Describe your suggestion

I encountered an issue while attempting to run the test in the [Simulating User Events](https://www.theodinproject.com/lessons/node-path-javascript-react-testing-part-1#simulating-user-events) section. The test failed and displayed the following error message: `TypeError: _userEvent.default.setup is not a function`. 

I'm using create-react-app for my project, which installs `"@testing-library/user-event": "^13.5.0"` by default. However, the test requires the latest version of `"@testing-library/user-event": "^14.4.3"` to utilize the `setup` function properly.

To resolve this issue, I executed the command `npm install --save-dev @testing-library/user-event@latest`. This updated the package to the latest version.

I suggest updating the documentation in the [Setting up](https://www.theodinproject.com/lessons/node-path-javascript-react-testing-part-1#setting-up) or providing a note regarding the necessary package version to prevent similar issues for learners using create-react-app.

Full error:
![Screenshot 2023-07-15 at 3 40 37 PM](https://github.com/TheOdinProject/curriculum/assets/104483181/b44bbb0d-a5cb-4817-9bcf-4733072fbc4f)

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-javascript-react-testing-part-1

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

mosmn

**Comment by Mclilzee** [comment] 2023-07-15 09:00
This issue already exist, check #25779

**Comment by ChargrilledChook** [comment] 2023-07-15 10:39
Thanks for the report @mosmn, someone is currently working on fixing this 👍

**Comment by ChargrilledChook** [comment] 2023-07-15 10:39
Duplicate of #25779

**Closed by ChargrilledChook** 2023-07-15 10:39 UTC

**Comment by mosmn** [comment] 2023-07-15 11:07
Noted.
