### ISSUE TITLE
[RoR] Blog App project can’t be carried out with latest 5.2x Rails stable release 

### ISSUE THREAD

**Issue by ghost** [TheOdinProject/curriculum#19611] opened 2020-07-28 08:16 UTC
Following through the [tutorial](http://tutorials.jumpstartlab.com/projects/blogger.html) for the Blog App, I got the following error when running `bin/rails console`:

```
Running via Spring preloader in process 4473
Traceback (most recent call last):
/home/remi/.gem/ruby/2.7.0/gems/spring-2.1.0/lib/spring/application.rb:175:in `fork': Bootsnap::LoadPathCache::FallbackScan
	42: from -e:1:in `<main>'
	41: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	40: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	39: from /home/remi/.gem/ruby/2.7.0/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:285:in `load'
	38: from /home/remi/.gem/ruby/2.7.0/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:257:in `load_dependency'
	37: from /home/remi/.gem/ruby/2.7.0/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:285:in `block in load'
	36: from /home/remi/.gem/ruby/2.7.0/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:55:in `load'
	35: from /home/remi/.gem/ruby/2.7.0/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:55:in `load'
	34: from /home/remi/web/the_odin_project/ruby_on_rails/blogger/bin/rails:9:in `<main>'
	33: from /home/remi/.gem/ruby/2.7.0/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:291:in `require'
	32: from /home/remi/.gem/ruby/2.7.0/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:257:in `load_dependency'
	31: from /home/remi/.gem/ruby/2.7.0/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:291:in `block in require'
	30: from /home/remi/.gem/ruby/2.7.0/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	29: from /home/remi/.gem/ruby/2.7.0/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	28: from /home/remi/.gem/ruby/2.7.0/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	27: from /home/remi/.gem/ruby/2.7.0/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	26: from /home/remi/.gem/ruby/2.7.0/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	25: from /home/remi/.gem/ruby/2.7.0/gems/railties-5.2.4.3/lib/rails/commands.rb:18:in `<main>'
	24: from /home/remi/.gem/ruby/2.7.0/gems/railties-5.2.4.3/lib/rails/command.rb:44:in `invoke'
	23: from /home/remi/.gem/ruby/2.7.0/gems/railties-5.2.4.3/lib/rails/command.rb:70:in `find_by_namespace'
	22: from /home/remi/.gem/ruby/2.7.0/gems/railties-5.2.4.3/lib/rails/command/behavior.rb:79:in `lookup'
	21: from /home/remi/.gem/ruby/2.7.0/gems/railties-5.2.4.3/lib/rails/command/behavior.rb:79:in `each'
	20: from /home/remi/.gem/ruby/2.7.0/gems/railties-5.2.4.3/lib/rails/command/behavior.rb:80:in `block in lookup'
	19: from /home/remi/.gem/ruby/2.7.0/gems/railties-5.2.4.3/lib/rails/command/behavior.rb:80:in `each'
	18: from /home/remi/.gem/ruby/2.7.0/gems/railties-5.2.4.3/lib/rails/command/behavior.rb:84:in `block (2 levels) in lookup'
	17: from /home/remi/.gem/ruby/2.7.0/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:291:in `require'
	16: from /home/remi/.gem/ruby/2.7.0/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:257:in `load_dependency'
	15: from /home/remi/.gem/ruby/2.7.0/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:291:in `block in require'
	14: from /home/remi/.gem/ruby/2.7.0/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	13: from /home/remi/.gem/ruby/2.7.0/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	12: from /home/remi/.gem/ruby/2.7.0/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	11: from /home/remi/.gem/ruby/2.7.0/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	10: from /home/remi/.gem/ruby/2.7.0/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	 9: from /home/remi/.gem/ruby/2.7.0/gems/railties-5.2.4.3/lib/rails/commands/console/console_command.rb:3:in `<main>'
	 8: from /home/remi/.gem/ruby/2.7.0/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:291:in `require'
	 7: from /home/remi/.gem/ruby/2.7.0/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:257:in `load_dependency'
	 6: from /home/remi/.gem/ruby/2.7.0/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:291:in `block in require'
	 5: from /home/remi/.gem/ruby/2.7.0/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:27:in `require'
	 4: from /home/remi/.gem/ruby/2.7.0/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:41:in `rescue in require'
	 3: from /home/remi/.gem/ruby/2.7.0/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	 2: from /home/remi/.gem/ruby/2.7.0/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/loaded_features_index.rb:89:in `register'
	 1: from /home/remi/.gem/ruby/2.7.0/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/home/remi/.gem/ruby/2.7.0/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require': cannot load such file -- irb (LoadError)
```
It looks like to be an issue with bootsnap but I can’t understand what exactly. I didn’t encounter problems on my system when going through My First Rails App.

OS: Parabola GNU+Linux
Ruby: 2.7.1
Rails: 5.2.4.3

**Comment by marvingay** [comment] 2020-11-15 18:55
Besides the fact that this user was using an unsupported operating system, I reviewed our Discord community chat history for issues regarding the Blog App, and this particular issue wasn't reproduced. Given the length of time since this issue's creation, closing.

**Closed by marvingay** 2020-11-15 18:55 UTC
