### ISSUE TITLE
self join exercise(9) in sqlzoo.net is broken

### ISSUE THREAD

**Issue by jithindasad** [TheOdinProject/curriculum#16925] opened 2020-05-10 08:45 UTC
Project: SQL under Databases section in TOP says to do Tutorials 0-9 listed under the “Tutorial Section” in sqlzoo.net. However, the self-join exercise in SQL Zoo seems to be broken.

**Details of database**
`stops(id, name)`
`route(num, company, pos, stop)`

**First exercise**
1. How many stops are in the database.

**Sample solution**
```
SELECT
  count(*)
FROM
  stops

```

**Error thrown**
`Invalid object name 'stops'.`

 _Site is not recognizing tables._

**Comment by marvingay** [comment] 2020-05-17 06:17
At the time of writing, this lesson has been verified to work as intended.
As an anecdote, it's imperative that the dropdown in the top-right (gear icon) is set to MySQL.

Closing.

**Closed by marvingay** 2020-05-17 06:17 UTC
