### ISSUE TITLE
Introduction to HTML and CSS: assignment link not working

### ISSUE THREAD

**Issue by Sreehari0o4** [TheOdinProject/curriculum#26705] opened 2023-11-09 15:14 UTC
### Describe your suggestion

The assignment link is not working . It takes to a website where no notes are provided . 

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-introduction-to-html-and-css

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

**Comment by xandora** [comment] 2023-11-09 19:46
Duplicate of #26696

**Closed by xandora** 2023-11-09 19:46 UTC
