### ISSUE TITLE
Rewrite HTML course

### ISSUE THREAD

**Issue by I3uckwheat** [TheOdinProject/curriculum#16011] opened 2020-04-16 15:19 UTC
More context: #13166 

The HTML course really could use a refresher.

**Comment by KevinMulhern** [comment] 2020-04-19 00:22
I think this should be the priority with the curriculum work right now. Imo it would be the best improvement we could make. It's one of the first subjects the student encounters and the later full course hasn't been touched in forever.

As a first step I think it would be prudent to make an outline of the lesson plan we want this new course to have so we have something concrete to start working towards.

**Comment by I3uckwheat** [comment] 2020-04-19 22:42
Here's some topics we may want to cover (in no particular order):

HTML
- a11y
- SEO/Header tags
- Semantic HTML (`<header>`, `<section>`, `<footer>`, etc) 
- Organization

CSS
- Flexbox
- Grid
- Floats (to understand what they are for, and how to work with the old style)
- Positioning
- Animations
- Designing

**Comment by HristovCodes** [comment] 2020-07-21 13:56
> * Designing

Double that. The course has thought me how to gather information and learn on my own but that doesn't mean it shouldn't have a section on designing. We are just told to experiment pretty much.

**Comment by HristovCodes** [comment] 2020-08-14 04:29
I can start working on flexbox, grid, positioning if no one has done them yet. I don't see any assignees and the issue is not closed so I guess it still needs to be worked on.

**Comment by SubliminalGuy** [comment] 2020-08-24 09:55
Hey! Regarding flexbox and grid, i think the _Additional Resources_ section in _HTML and CSS Basics_ could include links to the awesome free Scrimba videos: https://scrimba.com/course/gflexbox/enrolled and https://scrimba.com/course/gR8PTE/enrolled . They helped me a lot. I could edit the .md file if that is regarded helpful ...

**Comment by timkellytk** [comment] 2020-09-28 06:20
Hey @I3uckwheat, I'd be very interested in helping you re-write the HTML and CSS course. I have never contributed to an open-source project and I would love to get started. 

How do I get involved?

P.S. One easy win would be to remove this project from the curriculum -> [https://www.theodinproject.com/courses/html-and-css/lessons/design-your-own-grid-based-framework](https://www.theodinproject.com/courses/html-and-css/lessons/design-your-own-grid-based-framework). I hate to feel like I'm cheating the curriculum but I'm going to skip this project because this seems like a total waste of time with CSS grid and flexbox.

**Comment by I3uckwheat** [comment] 2020-09-28 13:11
@timkellytk 

That project is less about the grid, and more about learning how to organize CSS, it's important to remember that the end product isn't always the goal of a lesson.

There's a lot that needs to be done and we need someone experienced with HTML and CSS to lead this, but a good start would be to come up with concepts that are important to HTML and CSS.

**Comment by timkellytk** [comment] 2020-09-30 05:12
@I3uckwheat thanks for letting me know, that all makes complete sense. I'll keep grinding through the curriculum and come back when I've got enough experience.

**Comment by KevinMulhern** [comment] 2020-10-06 21:46
This is being planned, closing.

**Closed by KevinMulhern** 2020-10-06 21:46 UTC
Labels: Help Wanted
