### ISSUE TITLE
Natural Responsiveness Adv. HTML / CSS: Information behind a separate link

### ISSUE THREAD

**Issue by Mclilzee** [TheOdinProject/curriculum#27123] opened 2024-01-14 11:47 UTC
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

In the responsiveness lesson of the very first section [Learning Outcome](https://www.theodinproject.com/lessons/node-path-advanced-html-and-css-natural-responsiveness#learning-outcomes) we have a link that takes us to plain text HTML with no styling to demonstrate that an HTML with no CSS is responsive by default, [The Plain HTML Text](https://codyloyd.github.io/responsive-html/). I'm however afraid that students might skip the text that are in the demonstration as the demonstration itself doesn't indicate that it is informational and rather just showing the responsiveness.

Suggestions: 
- Add duplicate information of the site to the lesson, although this fix will make the reading of it repetetive for the people who actualy read the HTML page
- Extract the information from the link to be inside the lesson section itself and replace the HTML text with a placeholder like lorem porem
- Provide hint that the HTML Link contain important information

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-advanced-html-and-css-natural-responsiveness

### (Optional) Discord Name

mclilzee

**Comment by JoshDevHub** [comment] 2024-01-14 22:45
Hey @Mclilzee thank you for making this issue.

I agree that the text on the page is something that a user could possibly miss. I think your 3rd option where a note that tells the to make sure to read the page is the best route forward.

Since you didn't indicate that you want to work on this, I'll open this to other contributors. If you want to take this one, please comment below.

Acceptance Criteria:
- [ ] Add note around this link that tells users that they should read the page's text content

**Comment by Mclilzee** [comment] 2024-01-14 22:53
@JoshDevHub Thank you for taking a look at this issue. I think this would make a great first contribution which is why I left it so that people can be encouraged to work on issues for TOP which is a great push moving forward.

**Comment by Ariech** [comment] 2024-01-14 23:34
Great suggestion, @Mclilzee. I almost missed the information myself :) 
If the issue isn't picked up by someone who would like to try contributing for the first time, then I can work on it. However, I would like to give room to others and keep myself as a backup plan :)

**Comment by JoshDevHub** [comment] 2024-01-15 22:40
Good call that it'd be a nice issue for first time contributors. I'll slap the "good first issue" tag on it, and if someone hasn't picked it up within a week, I'll hand it over to you @Ariech :thumbsup:

**Comment by rosecodez** [comment] 2024-01-16 22:21
Hey guys i would love to work on this issue, it's my first time doing it and would love the experience :100:

**Comment by JoshDevHub** [comment] 2024-01-17 05:29
Hello @rosecodez 

Thank you for volunteering. I've assigned it to you. Let me know if you need any help.

**Closed** 2024-01-24 04:16 UTC
Labels: Type: Good First Issue, Content: Advanced HTML/CSS
