### ISSUE TITLE
Bug: Embedded code sandboxes do not include all intended files

### ISSUE THREAD

**Issue by CutlerSheridan** [TheOdinProject/curriculum#26268] opened 2023-07-29 00:11 UTC
Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `Bug: brief description of bug` format, e.g. `Bug: Lesson complete button does not update on click`

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**

The embedded code sandboxes are often described as having multiple files available for you to interact with, but, at least on the lesson pages where I've seen them, only include one each.

For example, in the ["Refs and Memoization" lesson](https://www.theodinproject.com/lessons/node-path-react-new-refs-and-memoization#the-usememo-hook), the sandbox should at least have the `App.jsx` file that contains the described components, but the only file present is `package-lock.json`, as seen in the below screenshot.

<img width="857" alt="Screenshot 2023-07-28 at 4 53 32 PM" src="https://github.com/TheOdinProject/theodinproject/assets/43424003/eeb1b556-d9ba-4fab-928f-151006e85fa8">

Additionally, in the ["Fetching Data in React" lesson](https://www.theodinproject.com/lessons/node-path-react-new-fetching-data-in-react#using-custom-hooks), the sandbox is stated to have a `Profile.jsx` file as well as a `Bio.jsx` component file, but only the former is present, as seen in this second screenshot below.  I have not checked other instances of the embedded code sandbox to see if this issue is omnipresent or isolated to these two instances.

<img width="825" alt="Screenshot 2023-07-28 at 4 53 55 PM" src="https://github.com/TheOdinProject/theodinproject/assets/43424003/24ac8264-0f0a-43e5-8c76-ccdca82ee142">

**2. How To Reproduce:**
1. Go to one of the previously linked lessons
2. Find the code sandbox
3. Try to find more files than those mentioned

**3. Expected Behavior:**
1. Go to one of the previously described lessons
2. Find the code sandbox
3. Play around with any of the files the text describes as being in the sandbox

**4. Desktop/Device:**

-   Device: 15" Macbook Pro 2018
-   OS: Ventura 13.4
-   Browser: Chrome
-   Version: 114.0.5735.198 (Official Build) (x86_64)

**5. Additional Information:**

**Comment by CouchofTomato** [comment] 2023-09-03 15:06
For me the sidebar was there. But there was an arrow I had to minimise first for Template Info. Super annoying. Happy to open this up to a clarification note if anyone wants to take it on

![image](https://github.com/TheOdinProject/curriculum/assets/12649577/240e0022-d061-40a8-a425-6f36fc08c703)

**Comment by Asartea** [comment] 2023-11-04 20:40
As I ran into this today and it seems to still be as confusing as before, could I be assigned this?

**Comment by CouchofTomato** [comment] 2023-11-06 15:46
@Asartea All yours mate :)

**Comment by Asartea** [comment] 2023-11-06 16:01
This appears to be fixed????? I know that as of this weekend this was an issue, but I can't reproduce this on either Firefox or Chrome anymore, and asking someone who hasn't done the course at all shows them the layout with everything showing.


![image](https://github.com/TheOdinProject/curriculum/assets/76259120/a2cc0880-c225-4b6d-8a74-1b3c8b5df1ec)

**Closed** 2023-11-06 16:10 UTC
Labels: Status: Help Wanted, Type: Bug, Content: React
