### ISSUE TITLE
Introduction/Join the Odin Community:  Broken link 404

### ISSUE THREAD

**Issue by zancorin** [TheOdinProject/curriculum#26768] opened 2023-11-18 18:15 UTC
### Describe your suggestion

The desert of despair link (https://www.thinkful.com/blog/why-learning-to-code-is-so-damn-hard/) is broken and results in 404 - page not found.

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-join-the-odin-community

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

zancorin

### (Optional) Additional Comments

Brought to our attention by 'thebatman' in the discord server. I'm willing to work on the issue if a correct link is found or if we are to remove this hyperlink* due to broken link.

**Comment by KevinMulhern** [comment] 2023-11-20 17:12
Thanks for reporting - duplicate of https://github.com/TheOdinProject/curriculum/issues/26753

**Closed by KevinMulhern** 2023-11-20 17:12 UTC
