### ISSUE TITLE
Intermediate HTML and CSS course: Add separate lesson for Form Styling

### ISSUE THREAD

**Issue by thatblindgeye** [TheOdinProject/curriculum#23639] opened 2022-02-21 00:06 UTC
- [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
- [x] The title of this issue follows the `where the change occurs: brief description of request` format, e.g. `Global SCSS file: Buttons should have XYZ`

- [ ] I would like to be assigned this issue to work on it

**1. Description of the Feature Request**

Currently, styling forms is lumped into the Intermediate HTML section, within the [Form Basics](https://www.theodinproject.com/paths/full-stack-javascript/courses/intermediate-html-and-css/lessons/form-basics) lesson. Since we already have another section for CSS concepts, and as a means to separate out some content, a separate lesson on Form Styling would be worth implementing.

Not only does it follow the "more lessons with less content per lesson" model, but it would reduce some of the extremely lengthy reading currently present in the Form Basics lesson. Some options to discuss regarding resolving this issue:

- Adding Form Styling alongside the current Form Basics and Form Validations lessons (within the Intermediate HTML section)
- Adding Form Styling in the Intermediate CSS section
- Creating an entirely new Forms section and placing Basics, Validation, and Styling, and the Project Sign-Up Form within it

**2. Additional Information**

**Comment by 01zulfi** [comment] 2022-02-21 03:33
A lesson on Form Styling sounds good. We can pull out the sections and assignments on form styling from the [Form Basics lesson](https://www.theodinproject.com/paths/full-stack-javascript/courses/intermediate-html-and-css/lessons/form-basics#a-note-on-styling-forms) and the [Form Validations lesson](https://www.theodinproject.com/paths/full-stack-javascript/courses/intermediate-html-and-css/lessons/form-validation#styling-validations) and put it in the new Form Styling lesson. Hopefully it should be enough content for the time being and we can reassess if we need to add more content to the lesson after it goes live. 

As for the placement, I believe it's ideal to have it after the Default Styles lesson in [Intermediate CSS Concepts section](https://www.theodinproject.com/paths/full-stack-javascript/courses/intermediate-html-and-css#intermediate-css-concepts).

**Comment by mgrigoriev8109** [comment] 2022-03-03 21:27
Not sure if zulfi was interested in working on this one - but if not then could I be assigned this issue?

**Comment by 01zulfi** [comment] 2022-03-04 07:12
@mgrigoriev8109  Thank you for showing interest and offering to work on this issue. Unfortunately, the issue is under discussion as signified by the "Status: Discussion" label. An acceptance criteria hasn't been decided yet.

If you have any thoughts, or any points of discussion you'd like to bring up regarding the issue, please feel free.

**Comment by mgrigoriev8109** [comment] 2022-03-04 11:38
I understand, apologies for improperly commenting, I'll pay closer attention to the tags in the future.

The only point of discussion I would have to offer is placement. If it seems like a good idea, I did notice going through the assignment that the second Forms Styling assignment, the internetingishard resource, uses properties like box-shadow. 

For this reason I wondered if it would be appropriate to place it after the More CSS Properties lesson, which introduced the box-shadow property

**Comment by thatblindgeye** [comment] 2022-04-09 15:44
@01zulfi @mgrigoriev8109 So personally, I think the best resolution might be creating an entirely new section in the Intermediate HTML and CSS course titled Forms. The structure of this course with such an update would end up looking like this:

1. Intermediate HTML Concepts
    - Same lessons as-is, except Form Basics and Form Validations are removed
2. Intermediate CSS Concepts
    - Same lessons as-is, except the Project is removed
4. Forms
    - Form Basics
    - Form Validations
    - Form Styling
    - Project: Sign-up Form
5. Grid

Of the available options, I think separating out the Form Styling lesson from the other Form lessons would break the flow too much (originally I believe this was where I was leaning, but Kevin and I believe Cody both made good points regarding this).

At the same time, while certain lessons unrelated to a section being added in can work (e.g. a Git lesson in the middle of an unrelated React section or something), I don't think it really would fit here.

Creating a separate section for Forms would retain the flow for those lessons, while also breaking the concept of Forms out to their own things as opposed to being lumped in with other concepts.

What are y'all's thoughts?

**Comment by 01zulfi** [comment] 2022-04-10 08:30
I agree with having a Forms section, @thatblindgeye

**Comment by mgrigoriev8109** [comment] 2022-04-12 00:07
I think this is a great idea @thatblindgeye :)

**Comment by 01zulfi** [comment] 2022-06-22 06:28
@thatblindgeye Any progress on how we want to tackle this?

**Comment by thatblindgeye** [comment] 2022-06-23 23:03
@01zulfi For now we should restructure the lessons in Intermediate HTML/CSS (noted in the issue linked above this comment in the website repo).

From there, a separate lesson on form styling can be added after the fact.

**Closed** 2022-06-27 06:28 UTC
Labels: Type: New Lesson, Status: Discussion
