### ISSUE TITLE
Feature: Create Custom Enumerable Project Test Cases

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/curriculum#22456] opened 2021-07-17 09:21 UTC
### Description
Create test cases the verify the student has correctly implemented each of their methods in [the custom enumerable project in the Ruby course](https://github.com/TheOdinProject/custom_enumerable_project).

We have set up a new repo for this here: https://github.com/TheOdinProject/custom_enumerable_project

* Use RSpec to add tests for each of the methods we instruct students to build in the project.
* Each methods test cases should be in their own spec file so students can run the tests for each method as they build them.
* Include a lib directory with an my_enumerables.rb file where the student is expected to implement their methods.

### Acceptance Criteria
1. On the project instruct the user to clone the custom enumerable project repo.
2. Instruct them to write their custom enumerables in the lib/my_enumerables.rb file of the repo.
3. Instruct them to run the tests for enumerable as they build them.

**Comment by rankoliang** [comment] 2021-07-20 03:28
I can work on this one! You ended up linking the repo twice. I assume it's this lesson in the course?https://www.theodinproject.com/paths/full-stack-ruby-on-rails/courses/ruby-programming/lessons/custom-enumerables

**Comment by KevinMulhern** [comment] 2021-07-21 13:12
Yeah thats the lesson, sorry @rankoliang I should have double checked those links before I posted. 

Thanks for taking this one on, if you have any questions about it don't hesitate to let me know.

**Comment by rankoliang** [comment] 2021-08-04 23:44
Just an update, I got a bit caught up with the game jam that I wasn't initially planning, but I'll get to working on this afterwards!

**Comment by rankoliang** [comment] 2021-08-10 20:45
@KevinMulhern I can't seem to fork or even make prs to the repository since it's empty. I'm not sure if there's something I'm missing since I don't have access to push to the repository directly or if I'll be able to submit a pr if I make my own repository that isn't a fork. Do you think you could add a license or empty readme to start it off?

**Comment by KevinMulhern** [comment] 2021-08-10 21:06
Apologies @rankoliang, I thought it would still allow you to fork it. I've sent you an invite to that repo mate.

**Comment by rankoliang** [comment] 2021-08-11 19:43
No worries, thank you!

**Comment by rankoliang** [comment] 2021-08-13 01:14
@KevinMulhern I've submitted a pr to the repository with my changes so far, if you wanted to see what I have. I also had some questions/found some issues I thought would be worth discussing; I just made test cases for the existing project instructions so far and can edit them if this repo seems good to point students to it.

- Currently, students are implementing `#my_each` on the `Enumerable` module. However, as far as I know, `Enumerable` does not implement an `#each` method as it is up to the class to provide it. Would it make more sense to have students implement `#my_each` on say `Hash` and `Array` instead? I could potentially write test cases to verify that their methods would work for both a hash and array in this case. Alternatively, I think we should at least clarify that `#my_each` only needs to work for an array.

- Some methods return an enumerator if a block is not given. I'm not sure if this was intended to be a requirement or not and looking at some of the submissions, I don't think many students handled that case properly either. Should we make it a requirement?

- The `my_map` method has three different versions throughout the project and I wasn't sure how to handle it. I made three spec files for each of the steps (takes a block, takes a proc, takes either/or or both). If they were in one file, students would have to skip and unskip specs as they change the functionality. I think we could potentially rework it a bit to make it more streamlined, but let me know if that is needed or if the way I did it is fine for now.

**Comment by KevinMulhern** [comment] 2021-08-13 05:54
Thanks for all your work on this @rankoliang, the tests are looking really good.

> Currently, students are implementing #my_each on the Enumerable module. However, as far as I know, Enumerable does not implement an #each method as it is up to the class to provide it. Would it make more sense to have students implement #my_each on say Hash and Array instead? I could potentially write test cases to verify that their methods would work for both a hash and array in this case. Alternatively, I think we should at least clarify that #my_each only needs to work for an array.

Yeah that makes a lot of sense, getting it working for just Array seems like the best approach for this initial version. Then we could maybe add it in for hash later if we needed to.

 > Some methods return an enumerator if a block is not given. I'm not sure if this was intended to be a requirement or not and looking at some of the submissions, I don't think many students handled that case properly either. Should we make it a requirement?

Just to keep things simple I think we shouldn't have it as a requirement for now.

> The my_map method has three different versions throughout the project and I wasn't sure how to handle it. I made three spec files for each of the steps (takes a block, takes a proc, takes either/or or both). If they were in one file, students would have to skip and unskip specs as they change the functionality. I think we could potentially rework it a bit to make it more streamlined, but let me know if that is needed or if the way I did it is fine for now.

I'll have a play with the tests this weekend, it would be ideal to have all the map related tests in the one spec so the students could test their map implementation in one go. But if theres no away around that, multiple specs will be fine.

**Comment by thatblindgeye** [comment] 2022-01-24 02:11
Closing this as it looks to have been completed and merged per [Custom Enumerable Project Test PR](https://github.com/TheOdinProject/custom_enumerable_project/pull/1)

**Closed by thatblindgeye** 2022-01-24 02:11 UTC
