### ISSUE TITLE
<JavaScript>: <Explictly state to not need to install ruby and rails at this point>

### ISSUE THREAD

**Issue by jw287962** [TheOdinProject/curriculum#25090] opened 2023-02-07 19:25 UTC
### Describe your suggestion

In this point of the course, under Initial Setup. It does say to READ the guide, which I know now to mean that you don't need to do it. 
but, I got confused and started to install the Ruby and Rails until someone pointed out else wise.

I think it would keep students on course, and prevent any misunderstandings to arise due to the conflictive steps on the secondary linked website.
Thanks,

![image](https://user-images.githubusercontent.com/28104428/217343854-b9de626c-66dc-4a0e-b969-982929200b20.png)

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/javascript-using-git-in-the-real-world

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

**Comment by xandora** [comment] 2023-02-09 01:36
These aren't instructions, they are a basic overview of how you might contribute to an opensource project using our own repository as an example. 

We could probably do more to make that clear in the lesson.

**Comment by kuromika** [comment] 2023-02-24 13:37
I wouldn't mind working on this making any corrections needed :)

**Comment by KevinMulhern** [comment] 2023-03-21 07:41
Duplicate of https://github.com/TheOdinProject/curriculum/issues/25035

**Closed by KevinMulhern** 2023-03-21 07:41 UTC
Labels: Status: Needs Triage, Content: Git
