### ISSUE TITLE
Growing and Shrinking: <404 error on the "video exploring how flexbox works and why.">

### ISSUE THREAD

**Issue by NorthernIndian** [TheOdinProject/curriculum#28239] opened 2024-06-18 17:15 UTC
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

There is a 404 error on the link at the bottom of the "Growing and Shrinking" page. The link is "video exploring how flexbox works and why."

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-growing-and-shrinking

**Comment by MaoShizhong** [comment] 2024-06-18 18:10
Duplicate of #28238

**Closed by MaoShizhong** 2024-06-18 18:10 UTC
