### ISSUE TITLE
Join the Odin Community: <Short description of your suggestion>

### ISSUE THREAD

**Issue by rramirez8** [TheOdinProject/curriculum#26401] opened 2023-10-01 23:14 UTC
### Describe your suggestion

When I click on the link to join discord, and then click on the accept invite button, I get an error saying safari can't open the link because the address is invalid.

### Path

Foundations

### Lesson Url

https://discord.gg/fbFCkYabZB

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### (Optional) Discord Name

hackysmack69

**Comment by ManonLef** [comment] 2023-10-02 09:28
do you have any issues joining other discords? I can't seem to reproduce this issue but that might be because I'm already a member.

**Comment by rramirez8** [comment] 2023-10-02 20:18
I am able to join other discord servers. Below is a screenshot of my error.

￼

**Comment by CouchofTomato** [comment] 2023-10-04 12:09
I'm sorry that you are having issues joining our Discord server. If you are accessing Discord through our website, the invitation should be valid and I've included it below:
https://discord.gg/fbFCkYabZB

In researching this online, it seems that message could be for a few other reasons

Discord could be down. You can visit Discord’s dedicated status page and see if there are ongoing issues on the platform. If Discord is down, there’s nothing you can do but wait since server-related issues can’t be fixed on your end.
https://discordstatus.com/

You’ve exceeded Your Discord Servers Limit. Discord has a limit on how many servers one user can be a member of at once. The maximum number of servers that you can join is 100. If you’re already at 100, you won’t be able to join another server.

You’re been banned from our Discord Server. This could happen if you've been part of our community before and your account got compromised, then starting spamming our channels. If this is a possibility, let me know what your discord username is and when you think your account was compromised.

If none of these options seem to be the issue, visit Discord’s Support page and get in touch with their team to report the issue you’ve been experiencing with the platform. Provide your account details, the server you want to join, and other necessary information to help Discord’s team assess the situation better.
https://support.discord.com/hc/en-us

**Comment by ManonLef** [comment] 2023-10-04 12:18
For both of your information, I did check the ban list and that does not seem to be the issue. I can’t find your username on that list 😊

**Comment by ManonLef** [comment] 2023-10-06 12:52
I will be closing this since I don't think the issue is on our end. Since Discord seems to be having invite issues on my end as well that are consistent with all invite links to servers I can find, here's one thing you could try:

![Image](https://github.com/TheOdinProject/curriculum/assets/81025586/51726141-1386-43f1-893c-4a302b9df2a3)

Copy the invite URL, go to the plus sign in Discord "Add a server" which will bring up the popup you see in the above image. Then click the button at the bottom "Join a server" and paste the invite link in the form field that shows up.

**Closed by ManonLef** 2023-10-06 12:52 UTC

**Comment by rramirez8** [comment] 2023-10-06 17:07
Thanks I’ll try itSent from my iPhoneOn Oct 6, 2023, at 7:52 AM, Manon ***@***.***> wrote:﻿
Closed #26401 as completed.

**Comment by rlmoser99** [comment] 2023-10-06 22:12
Could there have been another other users in your house (that share the same IP address) that could have joined our server and been banned (like if their account got hacked)?
