### ISSUE TITLE
Introduction To State: Missing code preview

### ISSUE THREAD

**Issue by CCSSD** [TheOdinProject/curriculum#27664] opened 2024-03-22 00:41 UTC
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

Out of credits
The workspace of the owner of this VM has run out of credits. Contact them to unlock the VM.
You can still fork this Devbox to your workspace to see it.

No code display on the first code part in Introduction To State | React course

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/node-path-react-new-introduction-to-state

**Comment by damon314159** [comment] 2024-03-22 01:42
Duplicate of #27253

**Comment by MaoShizhong** [comment] 2024-03-22 11:48
@CCSSD While we try to find the most sensible long-term solution for this, temporary instructions for how to use the Codesandbox VM have been added in #27666 and are now live in the lesson.

**Closed by MaoShizhong** 2024-03-22 11:48 UTC
