### ISSUE TITLE
Introduction To State: <Short description of your suggestion>

### ISSUE THREAD

**Issue by Ninja-Jutsu** [TheOdinProject/curriculum#27619] opened 2024-03-15 18:08 UTC
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

At [What is state in React?] section, I am asked to take  time reading the code as we’ll jump right in. Unfortunately, there is no code. A different website window is open there and shows nothing related to React. When trying to fork whatever is that, I get a error message saying that the VM ran out of credit. I am not sure if I am missing something or this part of the course is not updated! 

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-react-new-introduction-to-state

**Comment by MaoShizhong** [comment] 2024-03-15 21:29
Duplicate of #27253

@Ninja-Jutsu Thanks for opening this; we're aware of the issue and are exploring solutions for this.

In the meantime, you can simply hit "fork" in the codesandbox embed and sign in via github if you need to. If you're hit with an error e.g. `401 you are not authorized` or something similar, if you hit fork again then it should work.

**Closed by MaoShizhong** 2024-03-15 21:29 UTC
