### ISSUE TITLE
Linting: Need updated tutorials for VS Code and Sublime Text

### ISSUE THREAD

**Issue by czawojski** [TheOdinProject/curriculum#27833] opened 2024-04-21 17:22 UTC
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

The tutorials for VS Code and Sublime Text refer to previous versions of ESLint and plugins. I have been able to get ESLint working in the CLI but not in either editor. I'm no expert, for sure, but it seems that the configuration file that the VS Code tutorial refers to (.eslintrc.json) has been deprecated: https://eslint.org/docs/latest/use/configure/configuration-files-deprecated

Thank you for your help,
Christian

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-javascript-linting

### (Optional) Additional Comments

Thank you for offering a well-designed resource for learning to code!

**Comment by JoshDevHub** [comment] 2024-04-21 18:14
Thank you for making this issue.

As there's already an open ticket for this problem, I'm going to close this one so discussion can be consolidated in the original issue.

Duplicate of #27818

**Closed by JoshDevHub** 2024-04-21 18:14 UTC
