### ISSUE TITLE
Javascript Course: Fix the Code Tag for git command 'git remote add upstream'

### ISSUE THREAD

**Issue by mcabrera108** [TheOdinProject/curriculum#26572] opened 2023-10-26 21:16 UTC
### Describe your suggestion

In the 'Git in the Real World' Lesson -> under the 'Initial Setup' section -> list item #4 there is a large gap of space in the middle of the git command: 'git remote add upstream' and 'git@github.com:TheOdinProject/curriculum.git'. This causes the second part of the command to break into a new line.

![code-tag](https://github.com/TheOdinProject/curriculum/assets/31631896/791c4b4e-0354-4741-9032-61b3e8d7abb9)

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/javascript-using-git-in-the-real-world

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

**Comment by JoshDevHub** [comment] 2023-10-26 23:23
I agree that section doesn't look good. I've assigned you. Let me know if you need any help :+1:

**Comment by JoshDevHub** [comment] 2023-10-31 01:46
@mcabrera108 Sure. What do you need help with exactly? Setting up your fork/clone with github? Getting the command to look good?

I can't help with your problem if I don't know what the problem is.

**Comment by wise-king-sullyman** [comment] 2023-11-26 17:26
@mcabrera108 is this issue something you're still interested in resolving?

**Comment by aconstas** [comment] 2023-11-29 20:59
@wise-king-sullyman I'd love to help out with this issue!

**Comment by wise-king-sullyman** [comment] 2023-11-30 00:12
@aconstas I appreciate your enthusiasm!

I'd like to give the originally assigned person a few more days since my last ping though.

If they haven't responded here in the next four days ping me again and I'll be happy to assign you 🙂

**Comment by mcabrera108** [comment] 2023-11-30 02:36
Hello, @aconstas  I would appreciate the help. 

Apologies for not being active in this thread @wise-king-sullyman  as my regular job has had me backed up with work for the past couple of weeks and issues with github login. I should be free within the next couple of days to work on this issue.
 
My question is if you have a resource that you recommend to learn .md in order to fix this line as I haven't worked with .md files before.
![Screenshot_2023-11-29_20-33-09](https://github.com/TheOdinProject/curriculum/assets/31631896/b2bc9f5c-2929-4cbd-a6be-0a32ecda1a28)

**Comment by aconstas** [comment] 2023-11-30 02:38
@mcabrera108 Hey of course! If you'd like to chat on Discord my handle is @aconstas on there! I'd be happy to share some resources with you

**Comment by mcabrera108** [comment] 2023-12-06 23:38
Reposting my results here so that we're all on the same page about this issue. 

Hey @aconstas was working on the git issue and I noticed a couple of things that I wanted to run by you. Correct me if I'm wrong with any of this since I'm still learning haha
So first thing is that the root cause of this issue can possibly be attributed to how markdown is treating longer `<code>` element snippets with no spaces. For example: Say we have a long code snippet with no spaces git command THISISALARGEWORDTOTAKEUPASMUCHSPACEASPOSSIBLEFKJSDKKSFJSKDFJSKSJF. Markdown will place it in a separate line if this long word cannot fit in the previous line on your screen and this can lead to awkward results with large gaps in the previous sentence (on certain screens). I've noticed this formatting with regular text as well.
This issue isn't found on all display sizes, as a matter of fact, when I load this page on my other laptop it'll give me the proper formatting (image 1). However, if I were to adjust the page size to something like the second image (image 2 & 3), then it'll give me the same issue. Notice how bullet point three also has the same issue since it has a large git command with no spaces.

In conclusion, I think markdown is properly doing its job here by keeping long words in a separate line where it can fit properly.  However, it isn't consistent on all platforms. 

Some possible fixes to alleviate this specific issue can include:
-We can use a `<br>` to force the entire git command to into a new line. However, this can cause unintended results on different displays.
-We can use the `<pre>` element with a scroll effect (image 4) and place long git commands within it.

![image-1](https://github.com/TheOdinProject/curriculum/assets/31631896/830c6244-93bf-47fa-b493-fb0d7d5e5538)
![image-2](https://github.com/TheOdinProject/curriculum/assets/31631896/a24745c9-e1d3-4436-8ada-9f4e358d8c50)
![image-3](https://github.com/TheOdinProject/curriculum/assets/31631896/daba35c2-b65e-406c-aaa1-7538a3791233)
![image-4](https://github.com/TheOdinProject/curriculum/assets/31631896/e35feb08-1a4b-4258-9990-bd2fe74527cd)

**Comment by wise-king-sullyman** [comment] 2023-12-10 02:17
Hey @mcabrera108! No worries about the level of activity, we're all volunteers here 🙂 

Hmm I'll have to think on these different resolutions you've proposed. One more to throw into the ring would be just putting these long commands into dedicated codeblocks like so: https://www.theodinproject.com/lessons/preview?uuid=d74c4fe3-8dfb-4254-8cfb-14dd94f2c7ba.

The reason I think I _might_ lean towards that is just that we generally prefer to keep formatting in markdown whenever possible. I'm not dead set on it though.

**Comment by mcabrera108** [comment] 2023-12-10 04:04
@wise-king-sullyman That's exactly what I'm thinking too. A dedicated codeblock can better suit these long commands. Especially for mobile users. Let me know what your decision is!

**Comment by wise-king-sullyman** [comment] 2023-12-12 02:25
I'd say go for it with the dedicated codeblock 🚀

**Comment by mcabrera108** [comment] 2023-12-12 10:46
Created pull request. Let me know if there are any changes that need to be made.

**Closed** 2023-12-12 21:16 UTC
Labels: Content: Git
