### ISSUE TITLE
Introduction to HTML and CSS: <Short description of your suggestion>

### ISSUE THREAD

**Issue by AndreyTskhay** [TheOdinProject/curriculum#26697] opened 2023-11-08 20:26 UTC
### Describe your suggestion

The link https://brytdesigns.com/html-css-javascript-whats-the-difference/ under "HTML vs CSS vs JavaScript" in Assignments is invalid.
![image](https://github.com/TheOdinProject/curriculum/assets/29030901/f229b88d-8af2-4332-88b7-a6aa072f07d4)

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-introduction-to-html-and-css

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

AndreyTskhay

**Comment by xandora** [comment] 2023-11-09 19:46
Duplicate of #26696

**Closed by xandora** 2023-11-09 19:46 UTC

**Comment by xandora** [comment] 2023-11-09 21:32
@AndreyTskhay Since you were the first to tick the box stating you'd like to work on this, do you want to raise a PR to fix this issue?
