### ISSUE TITLE
Problem Solving: <Short description of your suggestion>

### ISSUE THREAD

**Issue by kanjen22** [TheOdinProject/curriculum#26506] opened 2023-10-15 22:17 UTC
### Describe your suggestion

The link "[What is Pseudocoding](https://web.archive.org/web/20211229231605/https://www.vikingcodeschool.com/software-engineering-basics/what-is-pseudo-coding)"
Is not working.

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-problem-solving

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

**Comment by wise-king-sullyman** [comment] 2023-10-16 01:21
Thanks for taking the time to make this issue, but it looks like this is a duplicate of #26494 so I'll be closing it.

**Closed by wise-king-sullyman** 2023-10-16 01:21 UTC
