### ISSUE TITLE
Bug - :HTML Examples not visible in HTML excercises using CODEPEN

### ISSUE THREAD

**Issue by SemiSentientFungus** [TheOdinProject/curriculum#23741] opened 2022-03-09 13:39 UTC
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `Bug - location of bug: brief description of bug` format, e.g. `Bug - React section: Knowledge Checks don't link to resource`

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**

I've moved onto the intro HTML courses, and all the examples that make use of  CODEPEN to display the HTML have the text colour set to the same colour as the background, so the text is unreadable unless you highlight it.
I've checked in both Firefox and Chrome, as well as turning Dark Mode on and off, and the issue repeats

**2. How To Reproduce:**
1. Log in
2. Visit an of the HTML lessons that use CODEPEN to display the effects of HTML Code
3. Look at any of the CODEPEN HTML displays 

**3. Expected Behavior:**
1. Log in
2. Visit a lesson page
3. The text should be readable when you view the HTML examples

**4. Desktop/Device:**

-   Device: PC
-   OS: Kubuntu
-   Browser: FireFox
-   Version: 97.0.2

**5. Additional Information:**
![image](https://user-images.githubusercontent.com/98585105/157452749-14362a57-3b0f-4c8d-aa68-2eb4997dfcde.png)
![image](https://user-images.githubusercontent.com/98585105/157452779-cd0c06df-e931-4009-b193-133b9d31cad2.png)

**Comment by LeoKirasic** [comment] 2022-03-22 15:14
@SemiSentientFungus I can't seem to reproduce this. Can you confirm that you're still having this issue?

**Comment by thatblindgeye** [comment] 2022-07-01 19:15
I am also unable to reproduce this. @SemiSentientFungus if you can provide more details about how to reproduce please feel free to reply, but for now I will be closing this issue.

**Closed by thatblindgeye** 2022-07-01 19:15 UTC
Labels: Status: Awaiting Response, Type: Bug
