### ISSUE TITLE
Problem Solving: <Short description of your suggestion>

### ISSUE THREAD

**Issue by AbraaoGeraldo** [TheOdinProject/curriculum#28395] opened 2024-07-12 18:16 UTC
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

In the "Additional resourses" the second link is not working

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-problem-solving

### (Optional) Additional Comments

We love TOP

**Comment by aaelsay3d** [comment] 2024-07-13 00:36
I can confirm that this link is working on my side. It took long time to load at first, but works.

**Comment by AbraaoGeraldo** [comment] 2024-07-13 03:42
Thx!

Em sex., 12 de jul. de 2024 21:36, Abdelrahman Elsayed <
***@***.***> escreveu:

**Comment by JoshDevHub** [comment] 2024-07-13 04:58
Seems to be working fine on my end. I'll close this issue for now, but if you find you're still having issues with it, leave a comment and I'll reopen.

**Closed by JoshDevHub** 2024-07-13 04:58 UTC
