### ISSUE TITLE
Variables and Operators: Javascript Operators Link not working

### ISSUE THREAD

**Issue by warrenabayon** [TheOdinProject/curriculum#28751] opened 2024-09-06 16:17 UTC
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

Hi,, the link in the Assignment > Go through the following articles to deepen your knowledge  > No. 3 JavaScript operators(http://javascript.info/operators). is not working anymore 

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/foundations-variables-and-operators

**Comment by Asartea** [comment] 2024-09-06 16:36
The link seems to work for me, could you try again?

**Comment by warrenabayon** [comment] 2024-09-06 16:59
Hi yeah .. I tried it on my phone too ..still the same, the page link keep
on loading then it goes to Err_timed_out

**Comment by warrenabayon** [comment] 2024-09-06 17:03
Hi .. I tried using different ISP, the page  link is working.. thanks

**Comment by MaoShizhong** [comment] 2024-09-07 13:34
Closing since this is not reproducible. Glad you found a fix on your end :+1:

**Closed by MaoShizhong** 2024-09-07 13:34 UTC
