### ISSUE TITLE
Problem Solving: <Assignment Link to Viking Code School Article Broken>

### ISSUE THREAD

**Issue by azuwilliams** [TheOdinProject/curriculum#26508] opened 2023-10-16 06:52 UTC
### Describe your suggestion

The link does not lead to anything and googling the article mentioned yields no results.

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-problem-solving

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

**Comment by wise-king-sullyman** [comment] 2023-10-16 23:44
Thank you for reporting this issue but it looks like it's a duplicate of #26494 so I'll be closing it. If I'm incorrect please reopen.

**Closed by wise-king-sullyman** 2023-10-16 23:44 UTC
