### ISSUE TITLE
Growing and Shrinking: Error on Additional Resource link

### ISSUE THREAD

**Issue by gasparjuico** [TheOdinProject/curriculum#28241] opened 2024-06-19 07:16 UTC
### Checks

- [ ] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

There is a typo on the video link in the additional resource section. 

Link on the TOP website redirects to:
https://www.youtube.com/watchv=u044iM9xsWU&t=1s&pp=ugMICgJhchABGAE%3D

It should be:
https://www.youtube.com/watch?v=u044iM9xsWU&t=1s&pp=ugMICgJhchABGAE%3D

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-growing-and-shrinking

**Comment by MaoShizhong** [comment] 2024-06-19 11:31
Duplicate of #28238

**Closed by MaoShizhong** 2024-06-19 11:31 UTC
