### ISSUE TITLE
Data Types and Conditionals: Creating 4 Repls not free anymore

### ISSUE THREAD

**Issue by ElKekso** [TheOdinProject/curriculum#29059] opened 2024-11-07 12:24 UTC
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

Not the existence but also the creation of more than 3 different repls is not free anymore. Doing the fourth task is not possible with one free account.

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-data-types-and-conditionals

**Comment by MaoShizhong** [comment] 2024-11-07 14:33
Thanks for raising this. I'll close this one as it's a partial duplicate of   #29054 but please feel free to add anything there.

**Closed by MaoShizhong** 2024-11-07 14:33 UTC
