### ISSUE TITLE
<Setting up Git>: <Copy and Paste potential issue>

### ISSUE THREAD

**Issue by zaysflower** [TheOdinProject/curriculum#26187] opened 2023-08-22 19:16 UTC
### Describe your suggestion

When setting up our SSH KEy in Oracle VM VirtualBox, you may need to set the Shared Clipboard setting under devices to "Bidirectional" in order to be able to copy and past the SSH key from the terminal into the GitHub website.

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-setting-up-git

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Additional Comments

I noticed that this may help some people who are just starting the course as I got stuck because of that one small issue as well. Everything else went perfectly smooth. Thank you!

**Comment by CouchofTomato** [comment] 2023-08-24 08:39
Our instructions state to only use the VM for TOP things once installed so the intention would be that you use a browser in the VM.

@xandora Do you have any input on this?

**Comment by xandora** [comment] 2023-08-24 08:42
Yea, you'd only need this if you weren't following the instructions to use the browser inside the VM instead.

**Comment by ManonLef** [comment] 2023-08-28 09:24
I've closed this since it seems to be confirmed this is not an addition that's needed if you follow the instructions from the curriculum. Thanks for contributing either way :)

**Closed** 2023-08-28 09:23 UTC
