### ISSUE TITLE
Foundations: Broken link

### ISSUE THREAD

**Issue by GorkemKcmn** [TheOdinProject/curriculum#28958] opened 2024-10-14 12:16 UTC
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

https://www.theodinproject.com/lessons/foundations-introduction-to-web-development
Cant access to [“Why Learning to Code is So Damn Hard”](https://web.archive.org/web/20230630111131/https://www.thinkful.com/blog/why-learning-to-code-is-so-damn-hard/) because of the attack on web archive it could be changed with https://medium.com/@andrewlatta/why-learning-to-code-is-so-damn-hard-303eae632820

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-introduction-to-web-development

**Comment by MaoShizhong** [comment] 2024-10-14 14:21
Closing because duplicate of #28951

Also related regarding the medium link is #28018

@JoshDevHub have we had any updates on that with Erik?

**Closed by MaoShizhong** 2024-10-14 14:21 UTC
