### ISSUE TITLE
Introduction to Web Development: Reporting a bad link

### ISSUE THREAD

**Issue by abstractmindblue** [TheOdinProject/curriculum#26783] opened 2023-11-20 05:15 UTC
### Describe your suggestion

The webpage https://www.thinkful.com/blog/why-learning-to-code-is-so-damn-hard/ under the 'Conclusion' section of Odin's Introduction to Web Development isn't working anymore.

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-introduction-to-web-development

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Additional Comments

You can reach me here, if there is an opportunity to work with you on this. I'm a total novice though and had just started learning web development through Odin. It's my first day. :)

**Comment by KevinMulhern** [comment] 2023-11-20 17:13
Thanks for reporting - duplicate of https://github.com/TheOdinProject/curriculum/issues/26753

**Closed by KevinMulhern** 2023-11-20 17:13 UTC
