### ISSUE TITLE
Bug: Error in iframe "CodeSandbox: Out of Credits"

### ISSUE THREAD

**Issue by Cragt** [TheOdinProject/curriculum#27370] opened 2024-02-15 06:19 UTC
[Specific Page](https://www.theodinproject.com/lessons/node-path-react-new-introduction-to-state)

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] The title of this issue follows the `Bug: brief description of bug` format, e.g. `Bug: Lesson complete button does not update on click`
- [ ] Would you like to work on this issue?

### Bug description

When viewing the webpage, the codesandbox iframe diplays an error, "Out of credits. The workspace of the owner of this VM has run out of credits. Contact them to unlock the VM. You can still fork this Devbox to your workspace to see it."
Forking does not work, for TOP does not give authorization.

![image](https://github.com/TheOdinProject/theodinproject/assets/88582093/6ca77cb4-9735-4c00-8f99-3cbfadd879f9)

Note: This error does not occur on the following pages in which an embedded CodeSandbox iframe is found:
https://github.com/TheOdinProject/curriculum/blob/main/react/more_react_concepts/managing_state_with_context_api.md
https://github.com/TheOdinProject/curriculum/blob/main/react/more_react_concepts/refs_and_memoization.md
https://github.com/TheOdinProject/curriculum/blob/main/react/the_react_ecosystem/fetching_data_in_react.md

Using Firefox 122.0.1 on Win10.

### How to reproduce

1. Visit lesson page. 2. Scroll down to iframe.

### Expected behavior

The iframe displays an editable code environment hosted by codesandbox.io.

### What browsers are you seeing the problem on?

Firefox

### What OS are you using?

Windows

**Comment by KevinMulhern** [comment] 2024-02-27 22:53
Thanks @Cragt - duplicate of https://github.com/TheOdinProject/curriculum/issues/27253

**Closed by KevinMulhern** 2024-02-27 22:53 UTC
Labels: Type: Bug
