### ISSUE TITLE
Introduction To State: Disabled codepen

### ISSUE THREAD

**Issue by mrpeepernumber007** [TheOdinProject/curriculum#27638] opened 2024-03-19 13:01 UTC
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

The codepen in the "Introduction to State" in the React Course is disabled. There is a message that states "The workspace of the owner of this VM has run out of credits. Contact them to unlock the VM."

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-react-new-introduction-to-state

### (Optional) Discord Name

kataifos

**Comment by MaoShizhong** [comment] 2024-03-19 13:15
Closing this as it is a duplicate of #27253

@mrpeepernumber007 Thanks for opening this; we're aware of the issue and are exploring solutions for this.

In the meantime, you can simply hit "fork" in the codesandbox embed and sign in via github if you need to. If you're hit with an error e.g. `401 you are not authorized` or something similar, if you hit fork again then it should work.

**Closed by MaoShizhong** 2024-03-19 13:15 UTC
