### ISSUE TITLE
Basic Enumerable Methods: The link to the first task in the assignments of this lesson is not working

### ISSUE THREAD

**Issue by Seeido** [TheOdinProject/curriculum#28247] opened 2024-06-20 14:50 UTC
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

As the title suggests, the link to the first task in the assignments of this lesson is not working but can be accessed using the Wayback Machine.

### Path

Ruby / Rails

### Lesson Url

https://www.theodinproject.com/lessons/ruby-basic-enumerable-methods

### (Optional) Discord Name

@seeido

**Comment by mathdebate09** [comment] 2024-06-20 17:43
Hi! Are you exactly referring to this link [Map, Select, and Other Enumerable Methods](https://eriktrautman.com/posts/ruby-explained-map-select-and-other-enumerable-methods)? 
For me, the regular link works fine.

**Comment by SumonGFC** [comment] 2024-06-20 17:47
This also works for me now. It was not working before, but now the website is back up  I think.

**Comment by mathdebate09** [comment] 2024-06-20 17:54
Oh, there might've been a hosting outage at the original author's end unfortunately, that's not something TOP maintainers can help around with :(

**Comment by theSamyak** [comment] 2024-06-20 21:02
It seems the issue with the lesson link has been resolved now. Would you please close the issue?

**Comment by theSamyak** [comment] 2024-06-20 21:03
> This also works for me now. It was not working before, but now the website is back up I think.

If the issue with the lesson link has been resolved, would you please close the issue?

**Comment by MaoShizhong** [comment] 2024-06-20 21:09
Closing as the link seems to be working, and I cannot reproduce a broken link myself.

**Closed by MaoShizhong** 2024-06-20 21:09 UTC
