### ISSUE TITLE
Working with APIs: weatherapi.com included in lesson not available - 502 Bad Gateway

### ISSUE THREAD

**Issue by dxmooremelb** [TheOdinProject/curriculum#27532] opened 2024-03-03 07:25 UTC
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

It looks like the weatherapi website is no longer available/can't be accessed. So I cannot continue the lesson using the same details. Maybe we could follow suggestion of the open issue #26897 and replace the weatherapi with visual crossing's weather API

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-javascript-working-with-apis

**Comment by MaoShizhong** [comment] 2024-03-03 11:42
@dxmooremelb Thank you for opening this issue.
Since this is a duplicate of the open issue you linked, I will be closing this one but have commented on that issue as there has already been some discussion there.
Please feel free to add to that discussion with your thoughts!

**Closed by MaoShizhong** 2024-03-03 11:42 UTC
