### ISSUE TITLE
Codecademy Git Course Requires CC info

### ISSUE THREAD

**Issue by hobbes543** [TheOdinProject/curriculum#12232] opened 2019-09-14 01:26 UTC
The Codecademy course referenced in the Git basics lesson is part of a paid course.  While the specific lesson is allowed to be tried for free, Codecademy requires that you enter CC info to do so.  I think it would be best if an alternate source is found for this exercise.

**Comment by krupenja** [comment] 2019-09-16 17:02
Duplicate of https://github.com/TheOdinProject/curriculum/issues/12086

**Comment by leosoaivan** [comment] 2019-09-19 01:12
And related to #12108

**Closed by leosoaivan** 2019-09-19 01:12 UTC
