### ISSUE TITLE
Installing PostgreSQL: Emphasise on necessity of semicolon 

### ISSUE THREAD

**Issue by guudewie** [TheOdinProject/curriculum#28580] opened 2024-08-06 12:55 UTC
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

The "Installing PostgreSQL" lesson shows the following command to create a role database "CREATE DATABASE <username>;". The semicolon is necessary to make the command work. I think its advisable to mention this, and potentially even link a resource explaining when and when not to use semicolons.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/nodejs-installing-postgresql

### (Optional) Discord Name

guudewie

**Comment by MaoShizhong** [comment] 2024-08-07 16:27
Closing as essentially duplicate of #28550

**Closed by MaoShizhong** 2024-08-07 16:27 UTC
