### ISSUE TITLE
Introduction to HTML and CSS: Link no longer avaiable.

### ISSUE THREAD

**Issue by j-serrano98** [TheOdinProject/curriculum#26706] opened 2023-11-09 16:10 UTC
### Describe your suggestion

Hi, first link for the assignment is no longer work.  Please fix that.

Thanks! 

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-introduction-to-html-and-css

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

**Comment by xandora** [comment] 2023-11-09 19:46
Duplicate of #26696

**Closed by xandora** 2023-11-09 19:46 UTC
