### ISSUE TITLE
More Testing: That the "Mocking is a Code Smell" article be taken out

### ISSUE THREAD

**Issue by Dimitrije108** [TheOdinProject/curriculum#28584] opened 2024-08-06 19:53 UTC
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

Article in question: https://medium.com/javascript-scene/mocking-is-a-code-smell-944a70c90a6a

Reason:  It's incredibly heavy on terminology never encountered before which causes frustration when trying to understand. Spending 20 mins trying to understand 10 new terms/concepts in just one paragraph out of a very lengthy article isn't very effective learning imo. You're put in a position to try and parse everything sentence by sentence or accept you can't understand half the things they're talking about. I like to understand what they're talking about so then I can understand examples and conceptualize them in my mind. I can't do that in this article since every paragraph needs to be deciphered thoroughly.

E.g. "The strategy used by redux-saga is to use objects that represent future computations. The idea is similar to returning a monad, except that it doesn’t always have to be a monad that gets returned. Monads are capable of composing functions with the chain operation, but you can manually chain functions using imperative-style code, instead." 

I also checked discord questions about this article to confirm I wasn't the only one struggling with it. There were other people suggesting it was hard to read/shouldn't be in the "More Tests" section.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-javascript-more-testing

**Comment by MaoShizhong** [comment] 2024-08-06 21:28
Closing as it's a duplicate of #28355

Do feel free to add your comments to that issue if you feel there's more to add to it

**Closed by MaoShizhong** 2024-08-06 21:28 UTC
