### ISSUE TITLE
Introduction to Web Development: <broken link/update hyperlink address>

### ISSUE THREAD

**Issue by hrudabaga** [TheOdinProject/curriculum#26754] opened 2023-11-17 16:18 UTC
### Describe your suggestion

Hello!

The hyperlink in the phrase "Why Learning to Code is So Damn Hard" goes to a 404 page. 

Thank you!
hrudabaga

### Path

Foundations

### Lesson Url

https://www.thinkful.com/blog/why-learning-to-code-is-so-damn-hard/

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### (Optional) Additional Comments

So grateful for this platform and opportunity to learn coding!

**Comment by Swapnilnaique** [comment] 2023-11-17 20:24
I'd like to help here, though I was not able to find a working link.
it's in location : https://www.theodinproject.com/lessons/foundations-introduction-to-web-development

**Comment by Swapnilnaique** [comment] 2023-11-17 20:27
Issue already exists.
Duplicate of 26753

**Comment by 01zulfi** [comment] 2023-11-18 10:46
@hrudabaga Thank you for creating this issue. This has already been reported https://github.com/TheOdinProject/curriculum/issues/26753

**Closed by 01zulfi** 2023-11-18 10:46 UTC
