### ISSUE TITLE
Introduction to Web Development: <Short description of your suggestion>

### ISSUE THREAD

**Issue by n13lluss** [TheOdinProject/curriculum#26788] opened 2023-11-20 15:08 UTC
### Describe your suggestion

The last link “why coding is so damn hard” doesnt work

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-introduction-to-web-development

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

**Comment by KevinMulhern** [comment] 2023-11-20 17:14
Thanks for reporting - duplicate of https://github.com/TheOdinProject/curriculum/issues/26753

**Closed by KevinMulhern** 2023-11-20 17:14 UTC
