### ISSUE TITLE
Bug: "Fetching Data In React" Lesson: Page autoscrolls to "Managing multiple fetch requests" on Firefox

### ISSUE THREAD

**Issue by ben1499** [TheOdinProject/curriculum#27665] opened 2024-03-22 02:03 UTC
### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] The title of this issue follows the `Bug: brief description of bug` format, e.g. `Bug: Lesson complete button does not update on click`
- [ ] Would you like to work on this issue?

### Bug description

The page auto-scrolls to "Managing multiple fetch requests" on load. I have also tried it on private mode but the issue persists.This issue happens only on Firefox (I'm on version 124 on Ubuntu), I have only checked on Chrome and Firefox. 

Page link: https://www.theodinproject.com/lessons/node-path-react-new-fetching-data-in-react

### How to reproduce

1. Visit the page link on Firefox (signed it or signed out)

### Expected behavior

1. Visit the lesson page (link provided)
2. Browser should display top of the page

### What browsers are you seeing the problem on?

Firefox

### What OS are you using?

Ubuntu

**Comment by KevinMulhern** [comment] 2024-03-22 08:12
Thanks for reporting @ben1499. I transferred this to the curriculum repo since this appears to be a content issue.

It's the cookie pop up within the Code Sandbox iframe doing it:

<img width="785" alt="Screenshot 2024-03-22 at 08 09 49" src="https://github.com/TheOdinProject/theodinproject/assets/7963776/49cc7366-8fb4-49eb-b92c-efc1f9600d52">

Confirmed by removing it in a lesson preview: https://www.theodinproject.com/lessons/preview?uuid=9203358b-9cc8-40f2-9fab-7c7edbe2a548

**Comment by xandora** [comment] 2024-03-22 22:50
Good Guy Firefox making sure you see *alllll* the cookies before using a website. 🙄

**Comment by MaoShizhong** [comment] 2024-03-28 19:54
AFAIK there isn't really anything we can do about this, is there?
There's no autoscroll in Chrome. This seems to just be a Firefox behaviour (don't know about any other browsers) and so is out of our control while we're still using codesandbox embeds, right?

If so, is this issue and the linked one closable?

**Comment by MaoShizhong** [comment] 2024-04-14 16:05
Closing as this just seems like browser-specific behaviour and the codesandbox cookie banner, which we won't be able to do anything about.

**Closed by MaoShizhong** 2024-04-14 16:05 UTC
Labels: Type: Bug
