### ISSUE TITLE
Function Basics: <Short description of your suggestion>

### ISSUE THREAD

**Issue by black23cat** [TheOdinProject/curriculum#27938] opened 2024-05-07 05:49 UTC
### Checks

- [ ] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

Assignment No.5 Javascript Call Stack link not found.

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-function-basics

**Comment by adhilkhan2023** [comment] 2024-05-07 06:15
this issue is a duplicate of a existing issue.

**Comment by MaoShizhong** [comment] 2024-05-07 14:08
Duplicate of #27937

**Closed by MaoShizhong** 2024-05-07 14:08 UTC
