### ISSUE TITLE
Natural Responsiveness: < Assignment Link Expired>

### ISSUE THREAD

**Issue by benjaAguilar** [TheOdinProject/curriculum#27992] opened 2024-05-17 16:06 UTC
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [x] Would you like to work on this issue?

### Describe your suggestion

the link to 3. [minmax() in auto-fill repeating tracks](https://gridbyexample.com/examples/example28/)
is not working

### Path

Other / NA

### Lesson Url

https://www.theodinproject.com/lessons/node-path-advanced-html-and-css-natural-responsiveness

### (Optional) Discord Name

color

**Comment by benjaAguilar** [comment] 2024-05-17 16:25
here is the link with the wayback machine that is actually working: https://web.archive.org/web/20240313111015/https://gridbyexample.com/examples/example28/

**Comment by MaoShizhong** [comment] 2024-05-17 17:25
Thanks for opening this issue @benjaAguilar. I've not been able to reproduce this. On my end with both computer and mobile, and on multiple browsers, the original link (https://gridbyexample.com/examples/example28/) loads the correct page for me.
Could you try clearing your browser cache and/or multiple browsers to see if you can replicate this issue?

Is anyone else able to replicate this issue as well?

**Comment by benjaAguilar** [comment] 2024-05-17 17:58
seems that the issue is with chromium or virtual machine because i tried on windows with multiple browsers and my mobile, and works fine.
I cleared the cache in chromium and the website still does not load.
also displayed the next error: 
![error](https://github.com/TheOdinProject/curriculum/assets/137722859/8b362c8e-820a-439a-8053-d5344e624e82)

**Comment by MaoShizhong** [comment] 2024-05-18 14:10
@benjaAguilar I've not been able to replicate this on a Xubuntu VM in Windows either. To me, this suggests a local DNS issue with your VM specifically which would probably be best asked in the Discord server in the virtualbox help channel, to see if there's anything you can do to flush or change the DNS configuration.

Since it can't otherwise be replicated and doesn't seem like something that we need to make changes to any of the curriculum files, I'll close this issue.

**Closed by MaoShizhong** 2024-05-18 14:10 UTC
