### ISSUE TITLE
React: Broken CodeSandbox example

### ISSUE THREAD

**Issue by autotelico** [TheOdinProject/curriculum#27273] opened 2024-02-03 23:17 UTC
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

In the React section, lesson **Introduction to State**([found here](https://www.theodinproject.com/lessons/node-path-react-new-introduction-to-state#what-is-state-in-react)), the CodeSandbox example right below states the following:

![image](https://github.com/TheOdinProject/curriculum/assets/44820991/7eae1367-4ffe-4ab6-b247-2d1e336c9b2b)

This modal won't allow the user to read the contents.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-react-new-introduction-to-state#what-is-state-in-react

### (Optional) Discord Name

autotelico

### (Optional) Additional Comments

I would enjoy working on the issue, as it would also be valuable experience to me. However, I don't know to what extent I could fix it, considering I'm not the owner. I propose to copy the code onto another platform, should I have access to its content.

**Comment by JoshDevHub** [comment] 2024-02-03 23:36
Duplicate of #27253

**Closed by JoshDevHub** 2024-02-03 23:36 UTC
