### ISSUE TITLE
Introduction To State: <CodeSandbox snippet not displaying>

### ISSUE THREAD

**Issue by DuraSky** [TheOdinProject/curriculum#27447] opened 2024-02-25 08:58 UTC
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

Hey,
There is a code snippet in the "[What is state in React?]" that is not working.

"Out of credits
The workspace of the owner of this VM has run out of credits. Contact them to unlock the VM.
You can still fork this Devbox to your workspace to see it."

Just wanted to make sure you guys are aware.

### Path

Other / NA

### Lesson Url

https://www.theodinproject.com/lessons/node-path-react-new-introduction-to-state

### (Optional) Discord Name

@durasky

**Comment by wise-king-sullyman** [comment] 2024-02-25 22:08
I think we'll have to change this CSB to be under the TOP CSB account to fix this, which will require a maintainer to do.

Thank you for reporting!

**Comment by KevinMulhern** [comment] 2024-02-27 22:54
Thanks for reporting @DuraSky - duplicate of https://github.com/TheOdinProject/curriculum/issues/27253

**Closed** 2024-02-27 22:54 UTC
Labels: Type: Maintainer Only
