### ISSUE TITLE
Deprecated instruction in linting JavaScript lesson

### ISSUE THREAD

**Issue by yamanidev** [TheOdinProject/curriculum#22706] opened 2021-09-24 17:33 UTC
Hello everyone.
On this [page](https://www.theodinproject.com/paths/full-stack-javascript/courses/javascript/lessons/linting)
You have a [link](http://shripalsoni.com/blog/configure-eslint-in-visual-studio-code/) that redirects to a blog, explaining how to set up eslint in VSCode.
The blog has a section that is deprecated under "Step 2: Enable ESLint In Your Workspace" which is "eslint.enable": true configuration.
Upon looking into this briefly I found it raised in a Github [issue](https://github.com/microsoft/vscode-eslint/issues/1150) of the official eslint repository:

"_Instead of using the eslint.enable setting you can now enable / disable ESLint using the extensions viewlet. That is why the setting is deprecated. If you have set it to true simply remove it. If set to false disable the extension for the corresponding workspace folder which will have the same effect._"

I apologize if my explanation is all over the place, I suck at it. Good luck!

**Comment by twalton83** [comment] 2021-09-24 17:34
Duplicate of #22096

**Comment by yamanidev** [comment] 2021-09-24 17:34
My bad. Should've checked the existing issues first.

**Closed by twalton83** 2021-09-24 17:34 UTC
