### ISSUE TITLE
Introduction To State: Fix broken CodeSandbox in state example

### ISSUE THREAD

**Issue by bartlett00** [TheOdinProject/curriculum#29213] opened 2024-12-19 16:29 UTC
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

There is a CodeSandbox embed that does not load, displaying an error that states: "The workspace of the owner of this VM has run out of credits. Contact them to unlock the VM." When attempting to fork, another error states "Failed to fork: (401) You don't have the needed authorization for this workspace (The Odin Project)."

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-react-new-introduction-to-state

**Comment by KevinMulhern** [comment] 2024-12-19 17:26
Thanks for reporting @bartlett00 - duplicate of https://github.com/TheOdinProject/curriculum/issues/29172

**Closed by KevinMulhern** 2024-12-19 17:26 UTC
