### ISSUE TITLE
Javascript > Brief Intro to CS: Linked quora discussion response might have changed

### ISSUE THREAD

**Issue by Im-Humor** [TheOdinProject/curriculum#26383] opened 2023-09-25 15:47 UTC
### Describe your suggestion

Assignment 3 in the Brief Intro to CS lesson states:

"3. Read [this Quora question about the importance of algorithms in web development](http://www.quora.com/Algorithms/What-is-the-importance-of-algorithms-in-web-development) to get some context for why we're going over this stuff."

When you open that link, the 'recommended' response is https://qr.ae/pK8GtW - which seems to state that algorithms are not useful in web development.

I wonder if this other response might have been the intended destination for students: https://qr.ae/pK8Ghc -> this seems to provide better context for why the lesson is important.

This is my first github issue I've ever submitted so I apologize if this is the wrong format, but perhaps linking directly to the intended response might be a better option?

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/javascript-a-very-brief-intro-to-cs

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### (Optional) Discord Name

_humor

**Comment by codyloyd** [comment] 2023-09-27 18:06
this is a duplicate of https://github.com/TheOdinProject/curriculum/issues/26219

closing this one in favor of the other.  Nice find though, and good suggestion!

**Closed by codyloyd** 2023-09-27 18:06 UTC
