### ISSUE TITLE
Introduction to HTML and CSS: <Short description of your suggestion>

### ISSUE THREAD

**Issue by gabedobb** [TheOdinProject/curriculum#26700] opened 2023-11-09 02:43 UTC
### Describe your suggestion

The website link in this lesson is no longer available (Introduction to HTML and CSS)

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-introduction-to-html-and-HTML vs CSS vs JavaScript

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

**Comment by xandora** [comment] 2023-11-09 19:46
Duplicate of #26696

**Closed by xandora** 2023-11-09 19:46 UTC
