### ISSUE TITLE
Introduction to Web Development: Broken link

### ISSUE THREAD

**Issue by oneninetyeight** [TheOdinProject/curriculum#26790] opened 2023-11-20 15:31 UTC
### Describe your suggestion

The link to the article "Why learning to code is so damn hard" is broken. I found a snapshot on the waybackmachine page here: https://web.archive.org/web/20230829114338/https://www.thinkful.com/blog/why-learning-to-code-is-so-damn-hard/

Hope this helps!

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-introduction-to-web-development

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

**Comment by KevinMulhern** [comment] 2023-11-20 17:14
Thanks for reporting - duplicate of https://github.com/TheOdinProject/curriculum/issues/26753

**Closed by KevinMulhern** 2023-11-20 17:14 UTC
