### ISSUE TITLE
Introduction To State: Out of credits

### ISSUE THREAD

**Issue by hansnery** [TheOdinProject/curriculum#27354] opened 2024-02-13 16:26 UTC
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### Describe your suggestion

CodeSandBox is not showing the code because it says it is out of credits.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-react-new-introduction-to-state

### (Optional) Discord Name

hansnery

**Comment by JoshDevHub** [comment] 2024-02-13 16:52
Duplicate of #27253

**Closed by JoshDevHub** 2024-02-13 16:52 UTC
