### ISSUE TITLE
Introduction to Web Development: broken link

### ISSUE THREAD

**Issue by alextiberi** [TheOdinProject/curriculum#26770] opened 2023-11-18 19:11 UTC
### Describe your suggestion

There is a broken link at the end of the article, it points to a 404 page.
- anchor text: “Why Is Coding So Damn Hard”
- destination URL: https://www.thinkful.com/blog/why-learning-to-code-is-so-damn-hard/

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/lessons/foundations-introduction-to-web-development

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### (Optional) Discord Name

Alex_aptDigital

### (Optional) Additional Comments

I considered offering to help find a replacement article but I’m a beginner and would not be qualified to judge the merit/value of a replacement piece of content.

**Comment by KevinMulhern** [comment] 2023-11-20 17:12
Thanks for reporting - duplicate of https://github.com/TheOdinProject/curriculum/issues/26753

**Closed by KevinMulhern** 2023-11-20 17:12 UTC
